version: '3.8'

services:
  app:
    build: .
    tty: true
    ports:
      - 3000:3000
    volumes: 
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --loglevel warning
    volumes: 
      - ./DB/redis:/data
